/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package insertionsort;

public class App {
    public static void main(String[] args) {
        if (args.length > 0)
            insertionSort(args);
        else
            System.out.println("Please provide some arguments");
    }

    public static String insertionSort(String[] args) {
        return "nada";
    }
}
